models/samples/wordpress/base/base.k, models/samples/wordpress/dev/kcl.yaml, models/samples/wordpress/dev/main.k, models/samples/wordpress/dev/stack.yaml, models/samples/wordpress/project.yaml
/kind feature
add the wordpress sample
Fixes #
```release-note
```
```docs
```
=> feat: add the wordpress sample

models/schema/v1/workload/service.k
/kind feature
feat: make ports as optional
Fixes #
```release-note
```
```docs
```
=> feat: make ports as optional

models/samples/helloworld/base/base.k, models/samples/wordpress/base/base.k, models/schema/v1/monitoring/prometheus.k, models/schema/v1/workload/network/port.k
/kind feature
add type in schema Port to support multiple clouds
=> feat: add type in schema Port to support multiple clouds

models/schema/v1/workload/secret/secret.k
/kind feature
add certificate secret type
Fixes #
```release-note
```
```docs
```
=> feat: support certificate secret type

models/schema/v1/accessories/database.k, models/schema/v1/app_configuration.k, models/schema/v1/workload/common.k, models/schema/v1/workload/container/probe/probe.k, models/schema/v1/workload/job.k, models/schema/v1/workload/secret/secret.k, models/schema/v1/workload/service.k
/kind chore
update attribute name and add missing comments
Fixes #
NONE
```release-note
```
```docs
```
=> chore: update attribute name and add missing comments

models/samples/helloworld/base/base.k, models/schema/v1/workload/secret/secret.k
/kind feature
support external secret type
Fixes #
```release-note
```
```docs
```
=> feat: support external secret type

models/samples/helloworld/base/base.k, models/samples/wordpress/base/base.k, models/schema/v1/workload/service.k
/kind feature
Do not expose type in schema Service.
=> feat: do not expose type in schema Service

models/samples/helloworld/base/base.k, models/samples/wordpress/base/base.k, models/schema/v1/workload/network/port.k
/kind feature
do not expose type in schema Port
=> feat: do not expose type in schema Port

models/schema/v1/trait/opsrule.k
Fixes #
```release-note
```
```docs
```
=> docs: upadte the opsrule

.github/PULL_REQUEST_TEMPLATE.md
/kind bug
fix pull request template spelling issue
Fixes #
```release-note
```
```docs
```
=> fix: pull request template spelling issue

models/samples/helloworld/base/base.k, models/schema/v1/workload/common.k, models/schema/v1/workload/network/port.k, models/schema/v1/workload/secret/secret.k
/kind feature
update secret types for better developer experience also add external secret
Fixes #
```release-note
```
```docs
```
=> feat: update secret types for better developer experience

models/samples/helloworld/base/base.k, models/schema/v1/workload/common.k, models/schema/v1/workload/secret/secret.k
/kind feature
revert last commit change for lower cognitive load
Fixes #
```release-note
```
```docs
```
=> feat: revert last commit for lower cognitive load

models/samples/helloworld/base/base.k, models/schema/v1/workload/secret/secret.k
/kind chore
revert sample code change
Fixes #
```release-note
```
```docs
```
=> chore: revert sample code change

models/schema/v1/workload/secret/secret.k
/kind fix
secret type data key mapping issue
Fixes #
```release-note
```
```docs
```
=> fix: secret type data key mapping issue

README.md
/kind documentation
update README.md add more description info
Fixes #
```release-note
```
```docs
```
=> feat: update README.md add more info

models/schema/v1/workload/common.k
Fixes #
```release-note
```
```docs
```
=> feat: replicas is optional in AppConfiguration

.gitignore, models/samples/prometheus/base/base.k, models/samples/prometheus/prod/kcl.yaml, models/samples/prometheus/prod/main.k, models/samples/prometheus/prod/stack.yaml, models/samples/prometheus/project.yaml, models/schema/v1/monitoring/prometheus.k
Fixes #
```release-note
```
```docs
```
=> refactor: updated monitoring schema to eliminate platform configs

models/schema/v1/accessories/mysql.k, models/schema/v1/accessories/postgres.k, models/schema/v1/app_configuration.k, models/schema/v1/monitoring/prometheus.k, models/schema/v1/trait/opsrule.k, models/schema/v1/workload/container/container.k, models/schema/v1/workload/container/lifecycle/lifecycle.k, models/schema/v1/workload/container/probe/probe.k, models/schema/v1/workload/job.k, models/schema/v1/workload/network/port.k, models/schema/v1/workload/secret/secret.k, models/schema/v1/workload/service.k
Fixes #
```release-note
```
```docs
```
=> chore: update docstring with the correct example

README.md
/kind feature
This PR updates the README.md. 
Fixes #
```release-note
```
```docs
```
=> feat: udpate README.md

models/samples/hellocollaset/base/base.k, models/samples/helloworld/base/base.k, models/samples/pgadmin/base/base.k, models/samples/prometheus/base/base.k, models/samples/wordpress/base/base.k, models/schema/v1/app_configuration.k
Fixes #
```release-note
```
```docs
```
=> refactor: upgrade appconfig shchema and related samples

modules/opsrule/example/dev/kcl.mod, modules/opsrule/example/dev/workspace.yaml
Fixes #
```release-note
```
```docs
```
=> fix: upgrade opsrule version in the example

modules/postgres/kcl.mod
/kind chore
This PR adds `version` in `kcl.mod` for `postgres` module. 
Fixes #
```release-note
```
```docs
```
=> chore: add version for postgres

modules/workload/job/common.k, modules/workload/job/container/container.k, modules/workload/job/container/lifecycle/lifecycle.k, modules/workload/job/container/probe/probe.k, modules/workload/job/job.k, modules/workload/job/kcl.mod, modules/workload/job/kcl.mod.lock, modules/workload/job/secret/secret.k, modules/workload/service/common.k, modules/workload/service/container/container.k, modules/workload/service/container/lifecycle/lifecycle.k, modules/workload/service/container/probe/probe.k, modules/workload/service/kcl.mod, modules/workload/service/kcl.mod.lock, modules/workload/service/secret/secret.k, modules/workload/service/service.k
fix #https://github.com/KusionStack/kusion/issues/1106
=> feat: add the workload schema definition

.github/workflows/upload.yml
/kind feature
This PR add a workflow yml for GitHub Actions to upload changed modules to GitHub Packages. 
Fixes #
```release-note
```
```docs
```
=> feat: add workflow for pushing changed modules

.github/workflows/upload.yml, modules/mysql/kcl.mod, modules/network/kcl.mod, modules/postgres/kcl.mod
/kind bug
This PR fixes the `upload.yml` for GitHub Actions to upload modules. 
Fixes #
```release-note
```
```docs
```
=> fix: upload.yml for actions to upload modules

modules/workload/job/kcl.mod, modules/workload/service/kcl.mod
/kind feature
This PR updates the `service` and `job` modules to the version of `0.2.0`. 
Fixes #
```release-note
```
```docs
```
=> feat: update service and job modules

.github/workflows/upload.yml
/kind feature
This PR updates the Kusion CLI version downloaded in `upload` workflow yml. 
Fixes #
```release-note
```
```docs
```
=> feat: update kusion version in upload workflow

modules/job/kcl.mod, modules/service/kcl.mod
/kind feature
This PR updates the version of `service` and `job` modules. 
Fixes #
```release-note
```
```docs
```
=> feat: update service and job version

modules/inference/example/dev/example_workspace.yaml, modules/inference/example/dev/kcl.mod, modules/inference/kcl.mod, modules/inference/src/Makefile, modules/inference/src/inference_generator.go
/kind bug
Fixes #
```release-note
```
fix ollama image to be pulled; 
correct the naming of resources (including length and case); 
greatly change the commands to be executed in the container;
update inference module beta version
```docs
```
=> fix(inference): enable generated YAML matches the correct resources

modules/inference/example/dev/example_workspace.yaml, modules/inference/example/dev/kcl.mod, modules/inference/example/dev/main.k, modules/inference/kcl.mod, modules/inference/src/Makefile, modules/inference/src/inference_generator.go
/kind bug
Fixes #
```release-note
```
limit the container portName length; 
change env name;
finish the example;
update inference module beta version
```docs
```
=> fix(inference): fix portName and env name; finish the example

.github/workflows/cla.yaml
Fixes #
```release-note
```
```docs
```
=> chore: update cla to allow bots

modules/inference/example/dev/example_workspace.yaml, modules/inference/example/dev/kcl.mod, modules/inference/kcl.mod, modules/inference/src/Makefile, modules/inference/src/inference.go, modules/inference/src/ollama_frame.go, modules/inference/src/ollama_frame_test.go
/kind feature
Fixes #
```release-note
```
```docs
```
=> feat(inference): add a proxy to easily switch models
